### ISSUE TITLE
Deprecation error when trying to dump a variable that's an element criteria

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/kint#3]
> PHP User Warning – yii\base\ErrorException
> An exception (craft\errors\DeprecationException) was thrown in on line 98 while executing Kint Parser Plugin "Kint\Parser\IteratorPlugin". Error message: Looping through element queries directly has been deprecated. Use the `all()` function to fetch the query results before looping over them.

Unlike using `{% dd var %}`, Kint is unable to dump an element query as a deprecation error will be hit. I've had this on categories, entries etc.

If you have the setting to throw a hard exception when deprecation errors exist, this halts execution entirely.

**Comment by mildlygeeky** [comment]
Thanks @jamesmacwhite - I've spent some time looking at this, and it looks like this is because Kint, by default, sees that the Query is iterable, and then goes to it iterating over it, even though that is a deprecation in Craft 3. I can dig into Kint's docs, but I'm not sure there is going to be a way to tell it not to iterate over objects that throw a deprecation on iteration.

**Comment by engram-design** [comment]
Yep, not much we can do about this, I'd recommend the native `{{ dump() }}` or `{% dd %}` Twig alternatives.

**Comment by engram-design** [comment]
FYI, this seems to have been improved in [3.0.0](https://github.com/verbb/kint/releases/tag/3.0.0) for Craft 4.
