### ISSUE TITLE
No toolbar after installation

### ISSUE THREAD

**Issue by spencer-ki** [verbb/kint#4]
Hi there, I've tried installing via the Craft plugin store and via composer.  It appears to be installed, but I have not yet seen the Kint toolbar or anything rendered in the html.  What might I be missing? Craft CMS 3.6.4.1 with Kint 1.0.0

**Comment by engram-design** [comment]
Hard to say without looking at your setup, but it will require a proper HTML document with `<html><body>...`, otherwise it won't be output.

You'll also need to call one of the [templating](https://github.com/verbb/kint#templating) calls, as it won't appear without those unlike the Yii debug toolbar for example.
